<!DOCTYPE html>
<html lang="id">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>Bank Mini Tsamaniyah - SMKN 8 Jakarta</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
  <style>
    :root{--primary-green:#2C5F2D;--primary-dark-green:#1a3a1b;--primary-light-green:#97BC62;--accent-gold:#FFD93D;--accent-yellow:#ffc107;--accent-red:#dc3545;--bg-white:#ffffff;--bg-cream:#FFF8E7;--bg-light:#f8f9fa;--text-dark:#212529;--text-grey:#495057;--text-light:#6c757d;--border-light:#dee2e6;--shadow-soft:0 2px 8px rgba(0,0,0,.05);--shadow-medium:0 4px 16px rgba(0,0,0,.12);--shadow-strong:0 8px 32px rgba(0,0,0,.16);--gradient-green:linear-gradient(135deg,#2C5F2D 0%,#97BC62 100%);--gradient-gold:linear-gradient(135deg,#FFD93D 0%,#ffc107 100%);--gradient-cream:linear-gradient(135deg,#ffffff 0%,#FFF8E7 100%);}
    *{margin:0;padding:0;box-sizing:border-box}html,body{height:auto}body{font-family:'Segoe UI',Tahoma,Geneva,Verdana,sans-serif;background:var(--gradient-cream);color:var(--text-dark);overflow-x:hidden;overflow-y:auto;padding:24px 16px;position:relative}
    .bg-animation{position:fixed;inset:0;z-index:-1;overflow:hidden}.floating-shapes{position:absolute;inset:0}.shape{position:absolute;background:rgba(32,201,151,.08);border-radius:50%;animation:float 8s ease-in-out infinite}.shape:nth-child(1){width:100px;height:100px;top:10%;left:10%;animation-delay:0s}.shape:nth-child(2){width:150px;height:150px;top:60%;left:80%;animation-delay:2s}.shape:nth-child(3){width:80px;height:80px;top:80%;left:20%;animation-delay:4s}.shape:nth-child(4){width:120px;height:120px;top:30%;left:70%;animation-delay:1s}@keyframes float{0%,100%{transform:translateY(0) rotate(0)}50%{transform:translateY(-25px) rotate(5deg)}}
    .pattern-overlay{position:fixed;inset:0;z-index:-1;opacity:.03;background-image:repeating-linear-gradient(45deg,var(--primary-green) 0,var(--primary-green) 1px,transparent 1px,transparent 10px),repeating-linear-gradient(-45deg,var(--primary-green) 0,var(--primary-green) 1px,transparent 1px,transparent 10px);animation:patternSlide 20s linear infinite}@keyframes patternSlide{0%{background-position:0 0}100%{background-position:50px 50px}}
    .main-container{width:100%;max-width:1200px;margin:0 auto;display:grid;grid-template-columns:1fr 1fr;min-height:70vh;border-radius:24px;overflow:hidden;box-shadow:var(--shadow-strong);background:var(--bg-white);border:1px solid var(--border-light);position:relative}
    .info-side{background:var(--gradient-green);padding:3rem;display:flex;flex-direction:column;justify-content:center;position:relative;overflow:hidden;color:#fff}.info-side::before{content:'';position:absolute;inset:0;background:url('data:image/svg+xml,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" fill="%23ffffff10"><circle cx="50" cy="50" r="2"/></svg>');animation:sparkle 25s linear infinite;opacity:.4}@keyframes sparkle{0%{transform:translate(0,0)}100%{transform:translate(-100px,-100px)}}
    .info-side::after{content:'';position:absolute;top:-50%;right:-50%;width:100%;height:100%;background:radial-gradient(circle,rgba(255,217,61,.15) 0%,transparent 70%);animation:glow 4s ease-in-out infinite}@keyframes glow{0%,100%{transform:translate(0,0) scale(1)}50%{transform:translate(-20px,-20px) scale(1.1)}}
    .geometric-bg{position:absolute;inset:0;overflow:hidden;opacity:.1}.geo-shape{position:absolute;border:2px solid #fff}.geo-1{width:200px;height:200px;border-radius:50%;top:10%;left:-5%;animation:rotate 20s linear infinite}@keyframes rotate{0%{transform:rotate(0deg)}100%{transform:rotate(360deg)}}.geo-2{width:150px;height:150px;bottom:10%;right:-5%;transform:rotate(45deg);animation:pulse 3s ease-in-out infinite}@keyframes pulse{0%,100%{transform:rotate(45deg) scale(1)}50%{transform:rotate(45deg) scale(1.1)}}.geo-3{width:100px;height:100px;border-radius:50%;top:50%;left:50%;animation:float 6s ease-in-out infinite}
    .logo{display:flex;align-items:center;gap:1.2rem;margin-bottom:2.5rem;position:relative;z-index:1}.logo-icon{width:70px;height:70px;background:var(--gradient-gold);border-radius:50%;display:flex;align-items:center;justify-content:center;font-size:2rem;color:var(--primary-green);box-shadow:var(--shadow-medium);animation:logoPulse 3s infinite;position:relative}@keyframes logoPulse{0%,100%{transform:scale(1)}50%{transform:scale(1.05)}}.logo-icon::before{content:'';position:absolute;inset:-5px;border-radius:50%;border:2px solid rgba(255,217,61,.3);animation:ripple 2s ease-out infinite}@keyframes ripple{0%{transform:scale(1);opacity:1}100%{transform:scale(1.5);opacity:0}}.logo-text{font-size:2.2rem;font-weight:800;color:#fff;text-shadow:2px 2px 4px rgba(0,0,0,.2)}
    .school-info{background:rgba(255,255,255,.15);padding:2rem;border-radius:16px;margin-bottom:2.5rem;backdrop-filter:blur(10px);border:1px solid rgba(255,255,255,.2);position:relative;z-index:1;overflow:hidden}.school-info::before{content:'';position:absolute;top:0;left:-100%;width:100%;height:100%;background:linear-gradient(90deg,transparent,rgba(255,255,255,.1),transparent);animation:shine 3s ease-in-out infinite}@keyframes shine{0%{left:-100%}100%{left:200%}}.school-name{font-size:1.4rem;font-weight:700;margin-bottom:1rem;display:flex;align-items:center;gap:.8rem}.school-name i{font-size:1.2rem;color:var(--accent-yellow);animation:bounce 2s ease-in-out infinite}@keyframes bounce{0%,100%{transform:translateY(0)}50%{transform:translateY(-5px)}}.school-description{font-size:1.05rem;line-height:1.6;opacity:.9;margin-bottom:1rem}.school-address{font-size:.95rem;opacity:.9;display:flex;gap:.8rem;line-height:1.5}.school-address i{margin-top:.2rem;color:var(--accent-yellow)}
    .info-tagline{font-size:1.8rem;margin-bottom:1.5rem;font-weight:700;line-height:1.3;position:relative;z-index:1;text-shadow:2px 2px 4px rgba(0,0,0,.1)}.info-description{font-size:1.1rem;line-height:1.6;margin-bottom:2.5rem;opacity:.9;position:relative;z-index:1}
    .features{display:flex;flex-direction:column;gap:1.2rem;position:relative;z-index:1}.feature{display:flex;align-items:center;gap:1.2rem;padding:1.2rem;background:rgba(255,255,255,.1);border-radius:12px;backdrop-filter:blur(10px);transition:.3s;border:1px solid rgba(255,255,255,.15);position:relative;overflow:hidden}.feature::before{content:'';position:absolute;inset:0;background:linear-gradient(135deg,transparent 0%,rgba(255,255,255,.1) 100%);opacity:0;transition:opacity .3s}.feature:hover{background:rgba(255,255,255,.15);transform:translateX(8px);border-color:rgba(255,255,255,.25)}.feature:hover::before{opacity:1}.feature i{font-size:1.4rem;width:28px;text-align:center;color:var(--accent-yellow);filter:drop-shadow(0 2px 4px rgba(0,0,0,.2))}.feature-title{font-weight:600;margin-bottom:.3rem;font-size:1.1rem;color:#fff}.feature-desc{font-size:.95rem;opacity:.9;line-height:1.4;color:rgba(255,255,255,.95)}
    .action-side{padding:4rem 3rem;display:flex;flex-direction:column;justify-content:center;background:var(--bg-white);position:relative}.action-side::before{content:'';position:absolute;top:0;right:0;width:300px;height:300px;background:radial-gradient(circle,rgba(151,188,98,.08) 0%,transparent 70%);border-radius:50%}.action-side::after{content:'';position:absolute;bottom:0;left:0;width:200px;height:200px;background:radial-gradient(circle,rgba(255,217,61,.08) 0%,transparent 70%);border-radius:50%}
    .action-header{text-align:center;margin-bottom:3rem;position:relative;z-index:1}.action-title{font-size:2.5rem;font-weight:800;margin-bottom:1rem;background:var(--gradient-green);-webkit-background-clip:text;-webkit-text-fill-color:transparent;background-clip:text;position:relative;display:inline-block}.action-title::after{content:'';position:absolute;bottom:-10px;left:50%;transform:translateX(-50%);width:60px;height:4px;background:var(--gradient-gold);border-radius:2px}.action-subtitle{color:var(--text-grey);font-size:1.2rem;line-height:1.5}
    .action-cards{display:flex;flex-direction:column;gap:2rem;margin-bottom:3rem;position:relative;z-index:1}.action-card{background:linear-gradient(135deg,#f8f9fa 0%,#ffffff 100%);padding:2.5rem;border-radius:20px;text-align:center;border:2px solid transparent;transition:.3s;box-shadow:var(--shadow-soft);position:relative;overflow:hidden}.action-card::before{content:'';position:absolute;top:-50%;right:-50%;width:100%;height:100%;background:conic-gradient(from 0deg,transparent,rgba(151,188,98,.1),transparent);animation:cardRotate 4s linear infinite;opacity:0;transition:opacity .3s}@keyframes cardRotate{0%{transform:rotate(0deg)}100%{transform:rotate(360deg)}}.action-card:hover{transform:translateY(-5px);box-shadow:var(--shadow-medium);border-color:var(--primary-light-green)}.action-card:hover::before{opacity:1}
    .card-icon{width:80px;height:80px;background:var(--gradient-green);border-radius:50%;display:flex;align-items:center;justify-content:center;font-size:2rem;color:#fff;margin:0 auto 1.5rem;box-shadow:var(--shadow-medium);position:relative;z-index:1;animation:iconFloat 3s ease-in-out infinite}@keyframes iconFloat{0%,100%{transform:translateY(0)}50%{transform:translateY(-10px)}}.card-icon::after{content:'';position:absolute;inset:-8px;border-radius:50%;border:3px solid var(--primary-light-green);opacity:.3;animation:iconPulse 2s ease-out infinite}@keyframes iconPulse{0%{transform:scale(1);opacity:.3}100%{transform:scale(1.3);opacity:0}}.card-title{font-size:1.5rem;font-weight:700;margin-bottom:1rem;color:var(--text-dark);position:relative;z-index:1}.card-description{color:var(--text-grey);line-height:1.6;margin-bottom:1.5rem;font-size:1.05rem;position:relative;z-index:1}
    .btn{padding:1.2rem 2.5rem;border:none;border-radius:12px;font-size:1.1rem;font-weight:600;cursor:pointer;transition:.3s;display:flex;align-items:center;justify-content:center;gap:.8rem;position:relative;overflow:hidden;text-decoration:none;z-index:1}.btn::before{content:'';position:absolute;top:50%;left:50%;width:0;height:0;background:rgba(255,255,255,.2);border-radius:50%;transform:translate(-50%,-50%);transition:width .6s,height .6s;z-index:-1}.btn:hover::before{width:300px;height:300px}.btn-primary{background:var(--gradient-green);color:#fff;box-shadow:var(--shadow-soft)}.btn-primary:hover{transform:translateY(-2px);box-shadow:var(--shadow-medium)}.btn-outline{background:transparent;border:2px solid var(--primary-green);color:var(--primary-green)}.btn-outline:hover{background:var(--primary-green);color:#fff;transform:translateY(-2px)}.btn-gold{background:var(--gradient-gold);color:var(--primary-green);box-shadow:var(--shadow-soft)}.btn-gold:hover{transform:translateY(-2px);box-shadow:var(--shadow-medium)}
    .contact-info{background:linear-gradient(135deg,var(--bg-cream) 0%,#fff 100%);padding:2rem;border-radius:16px;text-align:center;border-left:4px solid var(--accent-yellow);position:relative;z-index:1;box-shadow:var(--shadow-soft)}.contact-title{font-weight:700;color:var(--text-dark);margin-bottom:1rem;display:flex;align-items:center;justify-content:center;gap:.8rem;font-size:1.2rem}.contact-address{color:var(--text-grey);line-height:1.6;font-size:1.05rem}.warning-text{color:var(--accent-red);font-weight:600;margin-top:1rem;display:flex;align-items:center;justify-content:center;gap:.5rem;animation:warningBlink 2s ease-in-out infinite}@keyframes warningBlink{0%,100%{opacity:1}50%{opacity:.7}}
    .stats-badge{position:absolute;top:1rem;right:1rem;background:var(--gradient-gold);padding:.5rem 1rem;border-radius:20px;color:var(--primary-green);font-weight:700;font-size:.85rem;box-shadow:var(--shadow-soft);z-index:2;animation:badgePulse 2s ease-in-out infinite}@keyframes badgePulse{0%,100%{transform:scale(1)}50%{transform:scale(1.05)}}
    .notification{position:fixed;top:1rem;right:1rem;padding:1rem 1.4rem;border-radius:12px;background:var(--gradient-green);color:#fff;box-shadow:var(--shadow-medium);display:flex;align-items:center;gap:.8rem;transform:translateX(400px);transition:transform .3s ease;z-index:1000}.notification.show{transform:translateX(0)}.notification i{font-size:1.2rem}
    @media (max-width: 1024px){.main-container{grid-template-columns:1fr;max-width:720px}.info-side{padding:2.5rem}.action-side{padding:3rem 2rem}}
    @media (max-width: 768px){.logo{flex-direction:column;text-align:center;gap:1rem}.logo-text{font-size:1.8rem}.info-tagline{font-size:1.5rem}.action-title{font-size:2rem}.action-cards{gap:1.5rem}.action-card{padding:2rem}.stats-badge{font-size:.75rem;padding:.4rem .8rem}}
    @media (max-width: 480px){body{padding:16px 10px}.info-side,.action-side{padding:1.6rem}.logo-icon{width:60px;height:60px;font-size:1.8rem}.school-info{padding:1.2rem}.card-icon{width:70px;height:70px;font-size:1.8rem}.action-title{font-size:1.6rem}.action-subtitle{font-size:1rem}.btn{padding:1rem 2rem;font-size:1rem}.stats-badge{position:static;margin-bottom:1rem;display:inline-flex}}
  </style>
</head>
<body>
  <div class="bg-animation"><div class="floating-shapes"><div class="shape"></div><div class="shape"></div><div class="shape"></div><div class="shape"></div></div></div>
  <div class="pattern-overlay"></div>
  <div class="notification" id="notification"><i class="fas fa-info-circle"></i><span id="notification-message">Selamat datang di Bank Mini Tsamaniyah</span></div>
  <div class="main-container">
    <div class="info-side">
      <div class="geometric-bg"><div class="geo-shape geo-1"></div><div class="geo-shape geo-2"></div><div class="geo-shape geo-3"></div></div>
      <div class="logo"><div class="logo-icon"><i class="fas fa-university"></i></div><div class="logo-text">Bank Mini Tsamaniyah</div></div>
      <div class="school-info">
        <div class="school-name"><i class="fas fa-graduation-cap"></i>SMKN 8 Jakarta</div>
        <p class="school-description">Program perbankan syariah edukatif yang dikelola oleh siswa SMKN 8 Jakarta untuk memberikan pengalaman praktis dalam dunia perbankan.</p>
        <div class="school-address"><i class="fas fa-map-marker-alt"></i><span>Jl. Raya Pejaten Pasar Minggu Jakarta Selatan 12510</span></div>
      </div>
      <h1 class="info-tagline">Solusi Perbankan Praktis untuk Komunitas Sekolah</h1>
      <p class="info-description">Layanan perbankan mini dengan prinsip syariah yang memberikan pengalaman belajar langsung tentang manajemen keuangan dan operasional perbankan.</p>
      <div class="features">
        <div class="feature"><i class="fas fa-shield-alt"></i><div><div class="feature-title">Sistem Terpercaya</div><div class="feature-desc">Dibimbing langsung oleh guru profesional dengan standar keamanan yang ketat</div></div></div>
        <div class="feature"><i class="fas fa-hand-holding-heart"></i><div><div class="feature-title">Prinsip Syariah</div><div class="feature-desc">Beroperasi dengan sistem perbankan syariah yang transparan dan adil</div></div></div>
        <div class="feature"><i class="fas fa-users"></i><div><div class="feature-title">Untuk Sekolah</div><div class="feature-desc">Khusus melayani siswa, guru, dan staf SMKN 8 Jakarta</div></div></div>
        <div class="feature"><i class="fas fa-book-open"></i><div><div class="feature-title">Edukasi Finansial</div><div class="feature-desc">Media pembelajaran praktik perbankan dan manajemen keuangan</div></div></div>
      </div>
    </div>
    <div class="action-side">
      <div class="stats-badge"><i class="fas fa-star"></i> Terpercaya</div>
      <div class="action-header"><h2 class="action-title">Akses Layanan Bank</h2><p class="action-subtitle">Pilih opsi yang sesuai dengan kebutuhan Anda</p></div>
      <div class="action-cards">
        <div class="action-card">
          <div class="card-icon"><i class="fas fa-user-check"></i></div>
          <h3 class="card-title">Sudah Punya Akun</h3>
          <p class="card-description">Masuk ke akun banking Anda untuk mengakses layanan perbankan online, melihat saldo, dan melakukan transaksi.</p>
          <a href="/login" class="btn btn-primary"><i class="fas fa-sign-in-alt"></i>Masuk ke Akun</a>
        </div>
        <div class="action-card">
          <div class="card-icon"><i class="fas fa-user-plus"></i></div>
          <h3 class="card-title">Belum Punya Akun</h3>
          <p class="card-description">Daftarkan diri Anda secara langsung di lokasi Bank Mini Tsamaniyah untuk mendapatkan akses layanan perbankan.</p>
          <button class="btn btn-outline" onclick="showLocationInfo()"><i class="fas fa-map-marker-alt"></i>Lihat Lokasi</button>
        </div>
      </div>
      <div class="contact-info" id="locationInfo" style="display:none">
        <div class="contact-title"><i class="fas fa-university"></i>Kunjungi Kami di Sekolah</div>
        <p class="contact-address"><strong>Bank Mini Tsamaniyah</strong><br>SMKN 8 Jakarta<br>Jl. Raya Pejaten Pasar Minggu<br>Jakarta Selatan 12510<br><br><i class="fas fa-clock"></i> Buka: Senin - Jumat, 08:00 - 14:00 WIB</p>
        <div class="warning-text"><i class="fas fa-exclamation-triangle"></i>Pendaftaran hanya bisa dilakukan secara langsung!</div>
      </div>
    </div>
  </div>
  <script>
    function showNotification(msg){const el=document.getElementById('notification');document.getElementById('notification-message').textContent=msg||'';el.classList.add('show');setTimeout(()=>el.classList.remove('show'),4000);}
    function showLocationInfo(){const box=document.getElementById('locationInfo');box.style.display='block';showNotification('Silakan kunjungi lokasi kami untuk pendaftaran akun');box.scrollIntoView({behavior:'smooth',block:'center'});}
    document.addEventListener('DOMContentLoaded',()=>{showNotification('Selamat datang di Bank Mini Tsamaniyah - SMKN 8 Jakarta');document.querySelectorAll('.action-card').forEach(c=>{c.addEventListener('mouseenter',()=>c.style.transform='translateY(-8px)');c.addEventListener('mouseleave',()=>c.style.transform='translateY(0)');});document.querySelectorAll('.btn').forEach(b=>{b.addEventListener('click',e=>{const r=document.createElement('span');const rect=b.getBoundingClientRect();const size=Math.max(rect.width,rect.height);r.style.width=r.style.height=size+'px';r.style.left=(e.clientX-rect.left-size/2)+'px';r.style.top=(e.clientY-rect.top-size/2)+'px';r.style.position='absolute';r.style.borderRadius='50%';r.style.background='rgba(255,255,255,.25)';r.style.pointerEvents='none';r.style.transform='scale(0)';r.style.transition='transform .6s, opacity .6s';b.appendChild(r);requestAnimationFrame(()=>{r.style.transform='scale(1)';r.style.opacity='0'});setTimeout(()=>r.remove(),600);});});document.querySelectorAll('.feature').forEach(f=>{f.addEventListener('mouseenter',()=>f.style.transform='translateX(10px)');f.addEventListener('mouseleave',()=>f.style.transform='translateX(0)');});});
  </script>
</body>
</html>